# Generated by Django 2.2.12 on 2021-12-10 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cure',
            fields=[
                ('images', models.CharField(auto_created=True, default='', max_length=500)),
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease', models.CharField(max_length=100)),
                ('medicine', models.CharField(max_length=100)),
            ],
        ),
    ]
