# Generated by Django 3.2.10 on 2021-12-10 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicino', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cure',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cure',
            name='images',
            field=models.CharField(max_length=500),
        ),
    ]
